INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '446970xxxx', 'Название направления 1');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '375099661x', 'Название направления 2');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '21116321xx', 'Название направления 3');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '7612816xxx', 'Название направления 4');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '47830xxxxx', 'Название направления 5');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '5799xxxxxx', 'Название направления 6');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '2944701xxx', 'Название направления 7');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '71192xxxxx', 'Название направления 8');
INSERT INTO PHONE_CODE VALUES(seq_phone_code.nextval, '47079xxxxx', 'Название направления 9');
